namespace MGCreator
{
	partial class Form1
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.components = new System.ComponentModel.Container();
			this.contextMenuStrip1 = new System.Windows.Forms.ContextMenuStrip(this.components);
			this.fIleToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.fontComb1 = new MGCreator.FontComb();
			this.contextMenuStrip1.SuspendLayout();
			this.SuspendLayout();
			// 
			// contextMenuStrip1
			// 
			this.contextMenuStrip1.BackColor = System.Drawing.Color.Black;
			this.contextMenuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.fIleToolStripMenuItem});
			this.contextMenuStrip1.Name = "contextMenuStrip1";
			this.contextMenuStrip1.Size = new System.Drawing.Size(93, 26);
			// 
			// fIleToolStripMenuItem
			// 
			this.fIleToolStripMenuItem.Name = "fIleToolStripMenuItem";
			this.fIleToolStripMenuItem.Size = new System.Drawing.Size(92, 22);
			this.fIleToolStripMenuItem.Text = "FIle";
			// 
			// fontComb1
			// 
			this.fontComb1.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.fontComb1.FontName = "";
			this.fontComb1.FormattingEnabled = true;
			this.fontComb1.Items.AddRange(new object[] {
            "235MKSD",
            "Adobe Arabic",
            "Adobe Caslon Pro",
            "Adobe Caslon Pro Bold",
            "Adobe Devanagari",
            "Adobe Fan Heiti Std B",
            "Adobe Fangsong Std R",
            "Adobe Garamond Pro",
            "Adobe Garamond Pro Bold",
            "Adobe Gothic Std B",
            "Adobe Hebrew",
            "Adobe Heiti Std R",
            "Adobe Kaiti Std R",
            "Adobe Ming Std L",
            "Adobe Myungjo Std M",
            "Adobe Naskh Medium",
            "Adobe Song Std L",
            "Agency FB",
            "Algerian",
            "AR CENA",
            "Arial",
            "Arial Black",
            "Arial Narrow",
            "Arial Rounded MT Bold",
            "Arial Unicode MS",
            "Bahnschrift",
            "Bahnschrift Condensed",
            "Bahnschrift Light",
            "Bahnschrift Light Condensed",
            "Bahnschrift Light SemiCondensed",
            "Bahnschrift SemiBold",
            "Bahnschrift SemiBold Condensed",
            "Bahnschrift SemiBold SemiConden",
            "Bahnschrift SemiCondensed",
            "Bahnschrift SemiLight",
            "Bahnschrift SemiLight Condensed",
            "Bahnschrift SemiLight SemiConde",
            "Baskerville Old Face",
            "Bauhaus 93",
            "Bell MT",
            "Berlin Sans FB",
            "Berlin Sans FB Demi",
            "Bernard MT Condensed",
            "Birch Std",
            "BIZ UDPゴシック",
            "BIZ UDP明朝 Medium",
            "BIZ UDゴシック",
            "BIZ UD明朝 Medium",
            "Blackadder ITC",
            "Blackoak Std",
            "Bodoni MT",
            "Bodoni MT Black",
            "Bodoni MT Condensed",
            "Bodoni MT Poster Compressed",
            "Book Antiqua",
            "Bookman Old Style",
            "Bookshelf Symbol 7",
            "Bradley Hand ITC",
            "Britannic Bold",
            "Broadway",
            "Brush Script MT",
            "Brush Script Std",
            "Calibri",
            "Calibri Light",
            "Californian FB",
            "Calisto MT",
            "Cambria",
            "Cambria Math",
            "Candara",
            "Candara Light",
            "Cascadia Code",
            "Cascadia Code ExtraLight",
            "Cascadia Code Light",
            "Cascadia Code SemiBold",
            "Cascadia Code SemiLight",
            "Cascadia Mono",
            "Cascadia Mono ExtraLight",
            "Cascadia Mono Light",
            "Cascadia Mono SemiBold",
            "Cascadia Mono SemiLight",
            "Castellar",
            "Centaur",
            "Century",
            "Century Gothic",
            "Century Schoolbook",
            "Chaparral Pro",
            "Chaparral Pro Light",
            "Charlemagne Std",
            "Chiller",
            "Colonna MT",
            "Comic Sans MS",
            "Consolas",
            "Constantia",
            "Cooper Black",
            "Cooper Std Black",
            "Copperplate Gothic Bold",
            "Copperplate Gothic Light",
            "Corbel",
            "Corbel Light",
            "Courier New",
            "Curlz MT",
            "Didact Gothic",
            "Distant Stroke",
            "Dovetail MVB",
            "Dovetail MVB Extra Light",
            "Dovetail MVB Heavy",
            "Dovetail MVB Light",
            "Dovetail MVB Medium",
            "Dubai",
            "Dubai Light",
            "Dubai Medium",
            "Ebrima",
            "Edwardian Script ITC",
            "Elephant",
            "Engravers MT",
            "Eras Bold ITC",
            "Eras Demi ITC",
            "Eras Light ITC",
            "Eras Medium ITC",
            "Felix Titling",
            "Footlight MT Light",
            "Forte",
            "FOT-あられ Std DB",
            "FOT-グレコ Std B",
            "FOT-グレコ Std DB",
            "FOT-グレコ Std M",
            "FOT-ニューグレコ Std B",
            "FOT-ニューグレコ Std DB",
            "FOT-ニューグレコ Std M",
            "FOT-ニューシネマA Std D",
            "FOT-ニューシネマB Std D",
            "FOT-ニューロダン Pro B",
            "FOT-ニューロダン Pro DB",
            "FOT-ニューロダン Pro EB",
            "FOT-ニューロダン Pro L",
            "FOT-ニューロダン Pro M",
            "FOT-ニューロダン Pro UB",
            "FOT-ロダン Pro UB",
            "FOT-筑紫A丸ゴシック Std B",
            "FOT-筑紫A丸ゴシック Std D",
            "FOT-筑紫A丸ゴシック Std E",
            "FOT-筑紫A丸ゴシック Std L",
            "FOTAlphawave",
            "FOTAlphawave Bold",
            "FOTAlphawave Bold Italic",
            "FOTAlphawave Cond",
            "FOTAlphawave Italic",
            "FOTBullheaded",
            "FOTBullheaded Bold",
            "FOTBullheaded Bold Italic",
            "FOTBullheaded Cond",
            "FOTBullheaded Italic",
            "FOTComic Shop",
            "FOTComic Shop Bold",
            "FOTComic Shop Bold Italic",
            "FOTComic Shop Cond",
            "FOTComic Shop Italic",
            "FOTDretch",
            "FOTDretch Bold",
            "FOTDretch Bold Italic",
            "FOTDretch Cond",
            "FOTDretch Italic",
            "FOTDurion",
            "FOTDurion Bold",
            "FOTDurion Bold Italic",
            "FOTDurion Exp Bold",
            "FOTDurion Exp Italic",
            "FOTDurion Expanded",
            "FOTHarkin",
            "FOTHarkin Bold",
            "FOTHarkin Bold Italic",
            "FOTHarkin Exp Bold",
            "FOTHarkin Exp Italic",
            "FOTHarkin Expanded",
            "FOTKendrake",
            "FOTKendrake Bold",
            "FOTKendrake Bold Italic",
            "FOTKendrake Cond",
            "FOTKendrake Italic",
            "FOTMasterset",
            "FOTMasterset Bold",
            "FOTMasterset Bold Italic",
            "FOTMasterset Italic",
            "FOTNook",
            "FOTNook Bold",
            "FOTNook Bold Italic",
            "FOTNook Cond",
            "FOTNook Cond Bold",
            "FOTNook Cond Italic",
            "FOTNook Exp Bold",
            "FOTNook Exp Italic",
            "FOTNook Expanded",
            "FOTNook Italic",
            "FOTNook Nar Bold",
            "FOTNook Nar Italic",
            "FOTNook Narrow",
            "FOTNook Wide",
            "FOTNook Wide Bold",
            "FOTNook Wide Italic",
            "FOTShakies",
            "FOTShakies Bold",
            "FOTShakies Bold Italic",
            "FOTShakies Italic",
            "FOTSinkhole",
            "FOTSinkhole Bold",
            "FOTSinkhole Bold Italic",
            "FOTSinkhole Cond",
            "FOTSinkhole Italic",
            "Franklin Gothic Book",
            "Franklin Gothic Demi",
            "Franklin Gothic Demi Cond",
            "Franklin Gothic Heavy",
            "Franklin Gothic Medium",
            "Franklin Gothic Medium Cond",
            "Freestyle Script",
            "French Script MT",
            "FTT-Sニューロダン B",
            "FTT-Sニューロダン DB",
            "FTT-Sニューロダン EB",
            "FTT-Sマティス B",
            "FTT-Sマティス DB",
            "FTT-Sマティス EB",
            "FTT-カラット UB",
            "FTT-スーラ B",
            "FTT-スーラ DB",
            "FTT-スーラ EB",
            "FTT-スーラ L",
            "FTT-スーラ M",
            "FTT-スーラ UB",
            "FTT-マティスV B",
            "FTT-マティスV DB",
            "FTT-マティスV EB",
            "FTT-マティスV L",
            "FTT-マティスV M",
            "FTT-マティスV UB",
            "FTT-ロウディ EB",
            "FTT-筑紫AMゴシックL B",
            "FTT-筑紫AMゴシックS B",
            "Gabriola",
            "Gadugi",
            "Garamond",
            "GauFontRoot",
            "Georgia",
            "Giddyup Std",
            "Gigi",
            "Gill Sans MT",
            "Gill Sans MT Condensed",
            "Gill Sans MT Ext Condensed Bold",
            "Gill Sans Ultra Bold",
            "Gill Sans Ultra Bold Condensed",
            "Glam Queen ",
            "Gloucester MT Extra Condensed",
            "Goudy Old Style",
            "Goudy Stout",
            "Haettenschweiler",
            "HandelGothic BT",
            "Harlow Solid Italic",
            "Harrington",
            "HGP創英角ｺﾞｼｯｸUB",
            "HGP創英角ﾎﾟｯﾌﾟ体",
            "HGP創英ﾌﾟﾚｾﾞﾝｽEB",
            "HGP教科書体",
            "HGP明朝B",
            "HGP明朝E",
            "HGP行書体",
            "HGPｺﾞｼｯｸE",
            "HGPｺﾞｼｯｸM",
            "HGS創英角ｺﾞｼｯｸUB",
            "HGS創英角ﾎﾟｯﾌﾟ体",
            "HGS創英ﾌﾟﾚｾﾞﾝｽEB",
            "HGS教科書体",
            "HGS明朝B",
            "HGS明朝E",
            "HGS行書体",
            "HGSｺﾞｼｯｸE",
            "HGSｺﾞｼｯｸM",
            "HG丸ｺﾞｼｯｸM-PRO",
            "HG創英角ｺﾞｼｯｸUB",
            "HG創英角ﾎﾟｯﾌﾟ体",
            "HG創英ﾌﾟﾚｾﾞﾝｽEB",
            "HG教科書体",
            "HG明朝B",
            "HG明朝E",
            "HG正楷書体-PRO",
            "HG行書体",
            "HGｺﾞｼｯｸE",
            "HGｺﾞｼｯｸM",
            "High Tower Text",
            "Hind",
            "Hind Light",
            "Hind Medium",
            "Hind SemiBold",
            "Hobo Std",
            "HoloLens MDL2 Assets",
            "HP Simplified",
            "HP Simplified Light",
            "Impact",
            "Imprint MT Shadow",
            "Informal Roman",
            "Ink Free",
            "Javanese Text",
            "Jokerman",
            "Josefin Sans",
            "Josefin Sans ExtraLight",
            "Josefin Sans Light",
            "Josefin Sans Medium",
            "Josefin Sans SemiBold",
            "Josefin Sans Thin",
            "Juice ITC",
            "Kristen ITC",
            "Kunstler Script",
            "Leelawadee UI",
            "Leelawadee UI Semilight",
            "Letter Gothic Std",
            "Lithos Pro Regular",
            "Lordcorps Stencil",
            "Lucida Bright",
            "Lucida Calligraphy",
            "Lucida Console",
            "Lucida Fax",
            "Lucida Handwriting",
            "Lucida Sans",
            "Lucida Sans Typewriter",
            "Lucida Sans Unicode",
            "M+ 1c",
            "M+ 1c black",
            "M+ 1c heavy",
            "M+ 1c light",
            "M+ 1c medium",
            "M+ 1c thin",
            "M+ 1m",
            "M+ 1m light",
            "M+ 1m medium",
            "M+ 1m thin",
            "M+ 1mn",
            "M+ 1mn light",
            "M+ 1mn medium",
            "M+ 1mn thin",
            "M+ 1p",
            "M+ 1p black",
            "M+ 1p heavy",
            "M+ 1p light",
            "M+ 1p medium",
            "M+ 1p thin",
            "M+ 2c",
            "M+ 2c black",
            "M+ 2c heavy",
            "M+ 2c light",
            "M+ 2c medium",
            "M+ 2c thin",
            "M+ 2m",
            "M+ 2m light",
            "M+ 2m medium",
            "M+ 2m thin",
            "M+ 2p",
            "M+ 2p black",
            "M+ 2p heavy",
            "M+ 2p light",
            "M+ 2p medium",
            "M+ 2p thin",
            "Magneto",
            "Maiandra GD",
            "Malgun Gothic",
            "Malgun Gothic Semilight",
            "Marlett",
            "Matura MT Script Capitals",
            "Meiryo UI",
            "Mesquite Std",
            "Microsoft Himalaya",
            "Microsoft JhengHei",
            "Microsoft JhengHei Light",
            "Microsoft JhengHei UI",
            "Microsoft JhengHei UI Light",
            "Microsoft New Tai Lue",
            "Microsoft PhagsPa",
            "Microsoft Sans Serif",
            "Microsoft Tai Le",
            "Microsoft YaHei",
            "Microsoft YaHei Light",
            "Microsoft YaHei UI",
            "Microsoft YaHei UI Light",
            "Microsoft Yi Baiti",
            "MingLiU-ExtB",
            "MingLiU_HKSCS-ExtB",
            "Minion Pro",
            "Minion Pro Cond",
            "Minion Pro Med",
            "Minion Pro SmBd",
            "Mistral",
            "Modern No. 20",
            "Mongolian Baiti",
            "Monotype Corsiva",
            "MS Outlook",
            "MS Reference Sans Serif",
            "MS Reference Specialty",
            "MS UI Gothic",
            "MT Extra",
            "MV Boli",
            "Myanmar Text",
            "Myriad Arabic",
            "Myriad Hebrew",
            "Myriad Pro",
            "Myriad Pro Cond",
            "Myriad Pro Light",
            "NanumGothic",
            "NanumGothicExtraBold",
            "Niagara Engraved",
            "Niagara Solid",
            "Nirmala UI",
            "Nirmala UI Semilight",
            "NSimSun",
            "Nueva Std",
            "Nueva Std Cond",
            "OCR A Extended",
            "OCR A Std",
            "OCRB",
            "Old English Text MT",
            "Onyx",
            "Orator Std",
            "Palace Script MT",
            "Palatino Linotype",
            "Papyrus",
            "Parchment",
            "Perpetua",
            "Perpetua Titling MT",
            "Playbill",
            "PMingLiU-ExtB",
            "Poor Richard",
            "Poplar Std",
            "Prestige Elite Std",
            "Pristina",
            "Rage Italic",
            "Ravie",
            "Rexlia Rg",
            "Rockwell",
            "Rockwell Condensed",
            "Rockwell Extra Bold",
            "Rosewood Std Regular",
            "Script MT Bold",
            "Segoe MDL2 Assets",
            "Segoe Print",
            "Segoe Script",
            "Segoe UI",
            "Segoe UI Black",
            "Segoe UI Emoji",
            "Segoe UI Historic",
            "Segoe UI Light",
            "Segoe UI Semibold",
            "Segoe UI Semilight",
            "Segoe UI Symbol",
            "Showcard Gothic",
            "SimSun",
            "SimSun-ExtB",
            "Sitka Banner",
            "Sitka Display",
            "Sitka Heading",
            "Sitka Small",
            "Sitka Subheading",
            "Sitka Text",
            "Snap ITC",
            "Square721 BdEx BT",
            "Square721 BT",
            "Square721 Ex BT",
            "Stencil",
            "Stencil Std",
            "SunriseDCS Barcode",
            "SunriseDCS Morse",
            "SunriseDCS SDS font",
            "SunriseDCS Wave1",
            "SunriseDCS Wave2",
            "SunriseDCS Wave2 Bold",
            "SunriseDCS YOMENAI Alien",
            "SunriseDCS YOMENAI PC",
            "SunriseDCS YOMENAI Roman",
            "SunriseDCS YOMENAI Triangle",
            "Swis721 Blk2 BT",
            "Swis721 BlkEx BT",
            "Swis721 Ex BT",
            "Swis721 Hv BT",
            "Swis721 LtEx BT",
            "Swis721 Md BT",
            "Sylfaen",
            "Symbol",
            "Tahoma",
            "Tekton Pro",
            "Tekton Pro Cond",
            "Tekton Pro Ext",
            "Tempus Sans ITC",
            "Times New Roman",
            "Trajan Pro",
            "Trebuchet MS",
            "Tw Cen MT",
            "Tw Cen MT Condensed",
            "Tw Cen MT Condensed Extra Bold",
            "UD デジタル 教科書体 N-B",
            "UD デジタル 教科書体 N-R",
            "UD デジタル 教科書体 NK-B",
            "UD デジタル 教科書体 NK-R",
            "UD デジタル 教科書体 NP-B",
            "UD デジタル 教科書体 NP-R",
            "Verdana",
            "Viner Hand ITC",
            "Vivaldi",
            "Vladimir Script",
            "Webdings",
            "Wide Latin",
            "Wingdings",
            "Wingdings 2",
            "Wingdings 3",
            "Yu Gothic UI",
            "Yu Gothic UI Light",
            "Yu Gothic UI Semibold",
            "Yu Gothic UI Semilight",
            "ZEGAfont05",
            "ZWAdobeF",
            "ウソ電フォント-Kokutetsu",
            "ハイパースクエアU",
            "メイリオ",
            "小塚ゴシック Pr6N B",
            "小塚ゴシック Pr6N EL",
            "小塚ゴシック Pr6N H",
            "小塚ゴシック Pr6N L",
            "小塚ゴシック Pr6N M",
            "小塚ゴシック Pr6N R",
            "小塚ゴシック Pro B",
            "小塚ゴシック Pro EL",
            "小塚ゴシック Pro H",
            "小塚ゴシック Pro L",
            "小塚ゴシック Pro M",
            "小塚ゴシック Pro R",
            "小塚明朝 Pr6N B",
            "小塚明朝 Pr6N EL",
            "小塚明朝 Pr6N H",
            "小塚明朝 Pr6N L",
            "小塚明朝 Pr6N M",
            "小塚明朝 Pr6N R",
            "小塚明朝 Pro B",
            "小塚明朝 Pro EL",
            "小塚明朝 Pro H",
            "小塚明朝 Pro L",
            "小塚明朝 Pro M",
            "小塚明朝 Pro R",
            "游ゴシック",
            "游ゴシック Light",
            "游ゴシック Medium",
            "游明朝",
            "游明朝 Demibold",
            "游明朝 Light",
            "源ノ角ゴシック Code JP EL",
            "源ノ角ゴシック Code JP H",
            "源ノ角ゴシック Code JP L",
            "源ノ角ゴシック Code JP M",
            "源ノ角ゴシック Code JP N",
            "源ノ角ゴシック Code JP R",
            "源ノ角ゴシック JP",
            "ＤＦロマン雪W9",
            "ＤＦ優雅宋W7",
            "ＤＦ麗雅宋",
            "ＤＦＧロマン雪W9",
            "ＤＦＧ優雅宋W7",
            "ＤＦＧ麗雅宋",
            "ＤＦＰロマン雪W9",
            "ＤＦＰ優雅宋W7",
            "ＤＦＰ麗雅宋",
            "ＭＳ ゴシック",
            "ＭＳ 明朝",
            "ＭＳ Ｐゴシック",
            "ＭＳ Ｐ明朝"});
			this.fontComb1.Location = new System.Drawing.Point(206, 59);
			this.fontComb1.Name = "fontComb1";
			this.fontComb1.Size = new System.Drawing.Size(121, 23);
			this.fontComb1.TabIndex = 1;
			// 
			// Form1
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = System.Drawing.Color.Black;
			this.ClientSize = new System.Drawing.Size(621, 524);
			this.Controls.Add(this.fontComb1);
			this.Name = "Form1";
			this.Text = "Form1";
			this.Load += new System.EventHandler(this.Form1_Load);
			this.contextMenuStrip1.ResumeLayout(false);
			this.ResumeLayout(false);

		}

		#endregion

		private EditLayerLocation editControlPoint1;
		private EditLayerSize editControlSize1;
		private ContextMenuStrip contextMenuStrip1;
		private ToolStripMenuItem fIleToolStripMenuItem;
		private FontComb fontComb1;
	}
}